---
default_language_version:
  node: system

exclude: '(stacks/_templates/minio-.*/rendered-chart\.yaml|\.svg)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # 4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
        exclude: '^stacks/argo-cd-git-ops/secrets/sealed-secrets-key\.yaml$'

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1 # 1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.46.0 # 0.41.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0 # 0.10.0
    hooks:
      - id: shellcheck
        args: ["--severity=info"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.9 # 1.7.1
    hooks:
      - id: actionlint
